trigger:
- main

variables:
  imageName: 'medical-symptom-analyzer'

pool:
  name: 'Default'

steps:
- checkout: self

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-conn'  # <-- use your managed identity service connection name
    scriptType: 'ps'
    scriptLocation: inlineScript
    workingDirectory: '$(Build.SourcesDirectory)'    # <--- Add this line
    inlineScript: |
      az acr login --name symptomacr
      docker build -t symptomacr.azurecr.io/$(imageName):$(Build.BuildId) .
      docker push symptomacr.azurecr.io/$(imageName):$(Build.BuildId)
  displayName: 'Build and Push Docker Image to ACR' 
