apiVersion: v1
kind: Service
metadata:
  name: medical-symptom-analyzer-service
spec:
  type: LoadBalancer
  selector:
    app: medical-symptom-analyzer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
